from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Literal
from urllib.parse import quote

from pydantic import Field, model_validator

from .canonical import sha256_file
from .gate2_runtime_content import ACTIONS, REACTION_PARAMETERS
from .footprint_registry import resolve_actor_footprint
from .footprints import ActorFootprintProjection, project_actor_footprint
from .gate2_runtime_models import ActionDefinition, LegalCandidate, Position
from .map_calibration import MapVisualProjection, normalize_map_visual
from .models import StrictModel


PRESENTATION_SCHEMA = "TianxiaFactoryCombatPresentation.v1"
CHARACTER_AUTHORITY_SCHEMA = "TianxiaFactoryCombatCharacterAuthority.v1"


# Presentation metadata for system candidates that are already generated by the
# authoritative engine but do not have character-owned ActionDefinition records.
# Legality, destinations, and execution remain candidate/validator-owned.
SYSTEM_ACTION_PRESENTATIONS: dict[str, dict[str, str]] = {
    "system:combat.movement": {
        "display_name": "Move",
        "economy": "MOVEMENT",
        "resolution_kind": "MOVE",
        "target_kind": "DESTINATION",
    },
    "system:combat.hold_position": {
        "display_name": "Hold Position",
        "economy": "SYSTEM",
        "resolution_kind": "HOLD_POSITION",
        "target_kind": "SELF",
    },
    "system:combat.turn": {
        "display_name": "End Turn",
        "economy": "SYSTEM",
        "resolution_kind": "END_TURN",
        "target_kind": "SELF",
    },
}


def _humanize(value: str | None) -> str:
    if not value:
        return ""
    tail = str(value).split(":")[-1].split(".")[-1]
    return " ".join(part.capitalize() for part in tail.replace("-", "_").split("_") if part)


def _initials(display_name: str) -> str:
    pieces = [piece for piece in display_name.split() if piece]
    return "".join(piece[0] for piece in pieces[:2]).upper() or "?"


def _source_category(identifier: str, fallback: str = "ACTION") -> str:
    prefix = identifier.split(":", 1)[0].upper() if ":" in identifier else fallback
    return {
        "ACTION": "ACTION",
        "TALENT": "SPHERE_TALENT",
        "REACTION": "REACTION",
        "SYSTEM": "BASIC_ACTION",
        "CREATURE": "COMPANION_ACTION",
    }.get(prefix, fallback)


class PresentationFinding(StrictModel):
    code: str
    severity: Literal["INFO", "WARNING", "ERROR"]
    message: str
    actor_id: str | None = None
    action_definition_id: str | None = None


class DefenseProjection(StrictModel):
    defense_id: str
    display_name: str
    value: int


class ResourceProjection(StrictModel):
    resource_id: str
    display_name: str
    current: int
    maximum: int


class ConditionProjection(StrictModel):
    condition_id: str
    display_name: str
    stacks: int = 1
    source_definition_id: str | None = None
    expires_on: str | None = None


class VisualSnapshotProjection(StrictModel):
    kind: Literal["image", "initials"]
    public_url: str | None = None
    asset_id: str | None = None
    sha256: str | None = None
    initials: str | None = None
    source: str | None = None


class CharacterSheetRoute(StrictModel):
    available: bool
    route_kind: Literal["PERSISTENT_CHARACTER_SHEET", "CHARACTER_AUTHORITY_DETAILS"] | None = None
    character_sheet_identity: str | None = None
    route: str | None = None
    source_character_id: str | None = None
    source_revision_sha256: str | None = None
    finding: str | None = None


class ActionCostProjection(StrictModel):
    resource_id: str
    display_name: str
    amount: int


class ActionDefinitionProjection(StrictModel):
    action_definition_id: str
    runtime_source_definition_id: str
    display_name: str
    source_category: str
    economy: str
    resolution_kind: str
    target_kind: str
    range_ft: int | None = None
    reach_ft: int | None = None
    costs: tuple[ActionCostProjection, ...] = ()
    source_reference: str | None = None
    descriptive_summary: str | None = None
    reaction_parameters: dict[str, Any] | None = None


class ActionAvailabilityProjection(StrictModel):
    action_definition_id: str
    runtime_source_definition_id: str
    legal_now: bool
    candidate_ids: tuple[str, ...] = ()
    disabled_reason_codes: tuple[str, ...] = ()
    target_requirements: tuple[dict[str, Any], ...] = ()
    resource_options: tuple[str, ...] = ()
    current_constraints: tuple[str, ...] = ()
    reaction_trigger_context: dict[str, Any] | None = None


class CombatFeatureProjection(StrictModel):
    feature_id: str
    display_name: str
    category: str
    source_reference: str | None = None
    mechanics: dict[str, Any] = Field(default_factory=dict)


class CombatSheetProjection(StrictModel):
    entity_id: str
    source_character_id: str | None = None
    source_character_sheet_identity: str | None = None
    source_character_revision_sha256: str | None = None
    display_name: str
    team_id: str
    runtime_team_id: str
    team_display_name: str
    team_index: int
    primary_combatant: bool
    owner_id: str | None = None
    owner_display_name: str | None = None
    active: bool
    current_actor: bool
    controller: str
    character_summary: dict[str, Any] = Field(default_factory=dict)
    position: dict[str, int]
    footprint: ActorFootprintProjection
    hit_points: dict[str, int]
    defenses: tuple[DefenseProjection, ...]
    speed_ft: int
    movement_remaining_ft: int
    turn_state: dict[str, bool]
    resources: tuple[ResourceProjection, ...]
    conditions: tuple[ConditionProjection, ...]
    action_definitions: tuple[ActionDefinitionProjection, ...]
    action_availability: tuple[ActionAvailabilityProjection, ...]
    features: tuple[CombatFeatureProjection, ...]
    visual: VisualSnapshotProjection
    sheet_link: CharacterSheetRoute
    findings: tuple[PresentationFinding, ...] = ()


class TeamPresentation(StrictModel):
    team_id: str
    runtime_team_ids: tuple[str, ...]
    display_name: str
    team_index: int
    actor_ids: tuple[str, ...]


class BattlefieldGeometryProjection(StrictModel):
    battlefield_id: str
    display_name: str
    width_squares: int
    height_squares: int
    square_size_ft: int
    terrain_regions: tuple[dict[str, Any], ...]
    blocked_cells: tuple[dict[str, int], ...]
    cover_cells: tuple[dict[str, int], ...]
    hazard_cells: tuple[dict[str, int], ...]
    difficult_cells: tuple[dict[str, int], ...]
    mechanical_source_sha256: str


class HistoricalBoundaryProjection(StrictModel):
    boundary_index: int
    record_sequence: int | None = None
    transaction_id: str | None = None
    step_label: str
    canonical_state_sha256: str | None = None


class CombatPresentationProjection(StrictModel):
    schema_name: Literal[PRESENTATION_SCHEMA] = Field(default=PRESENTATION_SCHEMA, alias="schema")
    match_id: str
    display_name: str
    mode: Literal["LIVE", "HISTORY"]
    state_version: int
    boundary: HistoricalBoundaryProjection | None = None
    round_number: int
    current_slot_index: int
    current_actor_id: str | None = None
    paused: bool
    terminal: bool
    terminal_result: dict[str, Any] | None = None
    battlefield: BattlefieldGeometryProjection
    map_visual: MapVisualProjection | None = None
    teams: tuple[TeamPresentation, ...]
    actors: tuple[CombatSheetProjection, ...]
    initiative_order: tuple[str, ...]
    zones: tuple[dict[str, Any], ...]
    feed: tuple[dict[str, Any], ...]
    findings: tuple[PresentationFinding, ...] = ()

    @model_validator(mode="after")
    def validate_identity(self) -> "CombatPresentationProjection":
        actor_ids = [actor.entity_id for actor in self.actors]
        if len(actor_ids) != len(set(actor_ids)):
            raise ValueError("duplicate actor entity_id in presentation projection")
        if len(self.initiative_order) != len(set(self.initiative_order)):
            raise ValueError("duplicate initiative actor ID")
        missing = set(self.initiative_order) - set(actor_ids)
        if missing:
            raise ValueError(f"initiative references missing actors: {sorted(missing)}")
        if self.current_actor_id is not None and self.current_actor_id not in set(actor_ids):
            raise ValueError("current actor missing from presentation actors")
        return self


class CombatCharacterAuthorityProjection(StrictModel):
    schema_name: Literal[CHARACTER_AUTHORITY_SCHEMA] = Field(default=CHARACTER_AUTHORITY_SCHEMA, alias="schema")
    character_sheet_identity: str
    source_character_id: str
    source_revision_sha256: str
    projection_file_sha256: str
    projection: dict[str, Any]
    note: str = (
        "Exact accepted pre-combat character authority projection. Current HP, resources, "
        "conditions, action economy, and position remain authoritative only in the Combat Sheet."
    )


class CombatPresentationProjector:
    """Pure read-only normalization around the accepted combat runtime and snapshots."""

    def __init__(self, source_root: Path):
        self.source_root = Path(source_root).resolve()
        self.battlefield_path = self.source_root / "combat_gate1" / "generated" / "Battlefield.json"
        self._projection_by_actor: dict[str, dict[str, Any]] = {}
        self._projection_file_sha_by_actor: dict[str, str] = {}
        self._static_definition_by_actor: dict[str, dict[str, dict[str, Any]]] = {}
        for path in sorted((self.source_root / "combat_gate1" / "generated" / "projections").glob("*.json")):
            envelope = json.loads(path.read_text(encoding="utf-8"))
            projection = envelope["projection"]
            actor_id = str(projection["character_id"])
            self._projection_by_actor[actor_id] = envelope
            self._projection_file_sha_by_actor[actor_id] = sha256_file(path)
            definitions: dict[str, dict[str, Any]] = {}
            for category in (
                "actions", "reactions", "passives", "equipment_effects", "path_effects",
                "subpath_effects", "foundation_effects", "spheres", "talents", "companions",
                "condition_immunities", "resources",
            ):
                for row in projection.get(category) or []:
                    stable_id = row.get("stable_id")
                    if isinstance(stable_id, str):
                        definitions.setdefault(stable_id, {**row, "_category": category})
            self._static_definition_by_actor[actor_id] = definitions

    def character_authority(self, identity: str) -> CombatCharacterAuthorityProjection | None:
        prefix = "character_mapping:"
        if not identity.startswith(prefix):
            return None
        actor_id = identity[len(prefix):]
        envelope = self._projection_by_actor.get(actor_id)
        if envelope is None:
            return None
        return CombatCharacterAuthorityProjection(
            character_sheet_identity=identity,
            source_character_id=actor_id,
            source_revision_sha256=str(envelope["projection_sha256"]),
            projection_file_sha256=self._projection_file_sha_by_actor[actor_id],
            projection=envelope["projection"],
        )

    @staticmethod
    def _team_lookup(catalog: dict[str, Any]) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
        projection_by_actor = {
            str(row["runtime_entity_id"]): row for row in catalog.get("projections", [])
        }
        team_by_id = {str(row["team_id"]): row for row in catalog.get("teams", [])}
        return projection_by_actor, team_by_id

    def _resource_names(self, actor_id: str, owner_id: str | None) -> dict[str, str]:
        source_actor_id = owner_id or actor_id
        definitions = self._static_definition_by_actor.get(source_actor_id, {})
        return {
            stable_id: str(row.get("display_name") or _humanize(stable_id))
            for stable_id, row in definitions.items()
            if row.get("_category") == "resources"
        }

    def _visual(self, actor: dict[str, Any], metadata: dict[str, Any]) -> VisualSnapshotProjection:
        row = (metadata.get("visual_assets") or {}).get("tokens", {}).get(actor["entity_id"])
        if isinstance(row, dict) and row.get("public_url"):
            return VisualSnapshotProjection(
                kind="image",
                public_url=row.get("public_url"),
                asset_id=row.get("asset_id"),
                sha256=row.get("sha256"),
                initials=None,
                source=row.get("source") or "match_snapshot",
            )
        return VisualSnapshotProjection(kind="initials", initials=_initials(str(actor["display_name"])))

    def _sheet_route(
        self,
        actor: dict[str, Any],
        catalog_row: dict[str, Any] | None,
        findings: list[PresentationFinding],
    ) -> CharacterSheetRoute:
        if not actor.get("primary_combatant"):
            return CharacterSheetRoute(
                available=False,
                source_character_id=None,
                source_revision_sha256=None,
                finding="companion_has_no_independent_character_sheet",
            )
        identity = str((catalog_row or {}).get("character_sheet_identity") or "")
        actor_id = str(actor["entity_id"])
        expected = f"character_mapping:{actor_id}"
        if identity != expected:
            findings.append(PresentationFinding(
                code="missing_source_identity",
                severity="ERROR",
                actor_id=actor_id,
                message="The actor has no exact character-sheet identity matching its stable runtime ID.",
            ))
            return CharacterSheetRoute(
                available=False,
                character_sheet_identity=identity or None,
                source_character_id=actor_id,
                source_revision_sha256=actor.get("projection_sha256"),
                finding="missing_source_identity",
            )
        authority = self.character_authority(identity)
        if authority is None:
            findings.append(PresentationFinding(
                code="missing_character_authority_projection",
                severity="ERROR",
                actor_id=actor_id,
                message="The exact character authority projection is unavailable; no fuzzy route was substituted.",
            ))
            return CharacterSheetRoute(
                available=False,
                character_sheet_identity=identity,
                source_character_id=actor_id,
                source_revision_sha256=actor.get("projection_sha256"),
                finding="missing_character_authority_projection",
            )
        actor_revision = actor.get("projection_sha256")
        if actor_revision and actor_revision != authority.source_revision_sha256:
            findings.append(PresentationFinding(
                code="character_revision_mismatch",
                severity="ERROR",
                actor_id=actor_id,
                message="The match actor revision does not match the exact accepted character authority projection.",
            ))
            return CharacterSheetRoute(
                available=False,
                character_sheet_identity=identity,
                source_character_id=actor_id,
                source_revision_sha256=str(actor_revision),
                finding="character_revision_mismatch",
            )
        return CharacterSheetRoute(
            available=True,
            route_kind="CHARACTER_AUTHORITY_DETAILS",
            character_sheet_identity=identity,
            route=f"/api/combat/characters/{quote(identity, safe='')}",
            source_character_id=actor_id,
            source_revision_sha256=authority.source_revision_sha256,
        )

    @staticmethod
    def _definition_summary(static_row: dict[str, Any] | None) -> str | None:
        if not static_row:
            return None
        mechanics = static_row.get("mechanics")
        if not isinstance(mechanics, dict) or not mechanics:
            return None
        parts: list[str] = []
        for key in sorted(mechanics):
            value = mechanics[key]
            if isinstance(value, (str, int, float, bool)):
                parts.append(f"{_humanize(key)}: {value}")
            elif isinstance(value, list) and all(isinstance(item, (str, int, float, bool)) for item in value):
                parts.append(f"{_humanize(key)}: {', '.join(map(str, value))}")
        return " · ".join(parts[:5]) or None

    def _action_definition(
        self,
        actor_id: str,
        owner_id: str | None,
        action_key: str,
        runtime: ActionDefinition | None,
        resource_names: dict[str, str],
        findings: list[PresentationFinding],
    ) -> ActionDefinitionProjection:
        source_actor_id = owner_id or actor_id
        definitions = self._static_definition_by_actor.get(source_actor_id, {})
        runtime_source = runtime.source_definition_id if runtime is not None else action_key
        static_row = definitions.get(action_key) or definitions.get(runtime_source)
        if runtime is not None and action_key != runtime_source:
            findings.append(PresentationFinding(
                code="action_catalog_runtime_id_alias",
                severity="INFO",
                actor_id=actor_id,
                action_definition_id=action_key,
                message=(
                    "The actor catalog lookup ID differs from the runtime source-definition ID; "
                    "the exact typed alias is retained rather than matched by label."
                ),
            ))
        system_presentation = SYSTEM_ACTION_PRESENTATIONS.get(action_key)
        if runtime is None and action_key not in REACTION_PARAMETERS and system_presentation is None:
            findings.append(PresentationFinding(
                code="missing_action_definition",
                severity="ERROR",
                actor_id=actor_id,
                action_definition_id=action_key,
                message="No typed runtime action, system-candidate presentation, or reaction definition exists for this exact actor definition ID.",
            ))
        if runtime is not None:
            costs = tuple(
                ActionCostProjection(
                    resource_id=resource_id,
                    display_name=resource_names.get(resource_id, _humanize(resource_id)),
                    amount=amount,
                )
                for resource_id, amount in runtime.costs
            )
            return ActionDefinitionProjection(
                action_definition_id=action_key,
                runtime_source_definition_id=runtime_source,
                display_name=runtime.display_name,
                source_category=_source_category(action_key),
                economy=str(runtime.economy.value),
                resolution_kind=runtime.resolution_kind,
                target_kind=runtime.target_kind,
                range_ft=runtime.range_ft,
                reach_ft=runtime.reach_ft,
                costs=costs,
                source_reference=(static_row or {}).get("source"),
                descriptive_summary=self._definition_summary(static_row),
            )
        if system_presentation is not None:
            return ActionDefinitionProjection(
                action_definition_id=action_key,
                runtime_source_definition_id=action_key,
                display_name=system_presentation["display_name"],
                source_category="BASIC_ACTION",
                economy=system_presentation["economy"],
                resolution_kind=system_presentation["resolution_kind"],
                target_kind=system_presentation["target_kind"],
                costs=(),
                source_reference="Authoritative Gate 2 system candidate",
                descriptive_summary="Availability and legal choices are supplied only by the current engine candidate set.",
            )
        parameters = REACTION_PARAMETERS.get(action_key)
        return ActionDefinitionProjection(
            action_definition_id=action_key,
            runtime_source_definition_id=action_key,
            display_name=str((static_row or {}).get("display_name") or _humanize(action_key)),
            source_category="REACTION",
            economy="REACTION",
            resolution_kind="REACTION_CHECKPOINT",
            target_kind=str((parameters or {}).get("target") or "CONTEXTUAL"),
            costs=(),
            source_reference=(static_row or {}).get("source"),
            descriptive_summary=self._definition_summary(static_row),
            reaction_parameters=dict(parameters) if parameters else None,
        )

    @staticmethod
    def _availability(
        definition: ActionDefinitionProjection,
        actor: dict[str, Any],
        mode: Literal["LIVE", "HISTORY"],
        paused: bool,
        current_actor_id: str | None,
        candidates: tuple[LegalCandidate, ...],
    ) -> ActionAvailabilityProjection:
        relevant = tuple(
            candidate for candidate in candidates
            if candidate.actor_id == actor["entity_id"]
            and candidate.source_definition_id in {
                definition.runtime_source_definition_id,
                definition.action_definition_id,
            }
        )
        reasons: list[str] = []
        if mode == "HISTORY":
            reasons.append("historical_mode")
        elif paused:
            reasons.append("match_paused")
        elif not actor.get("active", False):
            reasons.append("actor_inactive")
        elif actor["entity_id"] != current_actor_id:
            reasons.append("not_current_actor")
        elif not relevant:
            reasons.append("no_engine_issued_candidate")
        legal = not reasons and bool(relevant)
        requirements = tuple({
            "candidate_id": candidate.candidate_id,
            "target_ids": list(candidate.target_ids),
            "destination": candidate.destination.model_dump(mode="json") if candidate.destination else None,
            "option_ids": list(candidate.option_ids),
            "kind": str(candidate.kind.value),
        } for candidate in relevant)
        option_ids = sorted({option for candidate in relevant for option in candidate.option_ids})
        constraints: list[str] = []
        if relevant:
            if any(candidate.target_ids for candidate in relevant):
                constraints.append("engine_validated_targets_only")
            if any(candidate.destination is not None for candidate in relevant):
                constraints.append("engine_validated_destinations_only")
        return ActionAvailabilityProjection(
            action_definition_id=definition.action_definition_id,
            runtime_source_definition_id=definition.runtime_source_definition_id,
            legal_now=legal,
            candidate_ids=tuple(candidate.candidate_id for candidate in relevant),
            disabled_reason_codes=tuple(reasons),
            target_requirements=requirements,
            resource_options=tuple(option_ids),
            current_constraints=tuple(constraints),
            reaction_trigger_context=(
                {"checkpoint": definition.reaction_parameters.get("checkpoint")}
                if definition.reaction_parameters else None
            ),
        )

    def _features(self, actor_id: str, owner_id: str | None) -> tuple[CombatFeatureProjection, ...]:
        source_actor_id = owner_id or actor_id
        definitions = self._static_definition_by_actor.get(source_actor_id, {})
        categories = {
            "passives": "PASSIVE",
            "equipment_effects": "EQUIPMENT",
            "path_effects": "PATH",
            "subpath_effects": "SUBPATH",
            "foundation_effects": "FOUNDATION",
            "spheres": "SPHERE",
            "talents": "TALENT",
        }
        rows: list[CombatFeatureProjection] = []
        for stable_id, row in sorted(definitions.items()):
            category = categories.get(str(row.get("_category")))
            if category is None:
                continue
            rows.append(CombatFeatureProjection(
                feature_id=stable_id,
                display_name=str(row.get("display_name") or _humanize(stable_id)),
                category=category,
                source_reference=row.get("source"),
                mechanics=dict(row.get("mechanics") or {}),
            ))
        return tuple(rows)

    def project(
        self,
        *,
        match_id: str,
        metadata: dict[str, Any],
        state: dict[str, Any],
        catalog: dict[str, Any],
        mode: Literal["LIVE", "HISTORY"],
        candidates: tuple[LegalCandidate, ...] = (),
        feed: tuple[dict[str, Any], ...] = (),
        boundary: dict[str, Any] | None = None,
    ) -> CombatPresentationProjection:
        projection_by_actor, team_by_id = self._team_lookup(catalog)
        presentation_findings: list[PresentationFinding] = []
        battlefield = next(
            (row for row in catalog.get("battlefields", []) if row.get("stable_id") == metadata.get("battlefield_id")),
            (catalog.get("battlefields") or [None])[0],
        )
        if not isinstance(battlefield, dict):
            raise ValueError("battlefield projection unavailable")
        terrain_regions = tuple(dict(row) for row in battlefield.get("terrain_regions", []))
        blocked: list[dict[str, int]] = []
        cover: list[dict[str, int]] = []
        hazard: list[dict[str, int]] = []
        difficult: list[dict[str, int]] = []
        for region in terrain_regions:
            cells = [dict(cell) for cell in region.get("cells", [])]
            terrain_type = region.get("terrain_type")
            if terrain_type == "BLOCKED":
                blocked.extend(cells)
            elif terrain_type == "SIMPLE_COVER":
                cover.extend(cells)
            elif terrain_type == "QI_HAZARD":
                hazard.extend(cells)
            if int(region.get("movement_cost", 1)) > 1:
                difficult.extend(cells)
        geometry = BattlefieldGeometryProjection(
            battlefield_id=str(battlefield["stable_id"]),
            display_name=str(battlefield["display_name"]),
            width_squares=int(battlefield["width_squares"]),
            height_squares=int(battlefield["height_squares"]),
            square_size_ft=int(battlefield.get("square_size_ft", 5)),
            terrain_regions=terrain_regions,
            blocked_cells=tuple(blocked),
            cover_cells=tuple(cover),
            hazard_cells=tuple(hazard),
            difficult_cells=tuple(difficult),
            mechanical_source_sha256=sha256_file(self.battlefield_path),
        )

        raw_map_visual = (metadata.get("visual_assets") or {}).get("map")
        map_visual: MapVisualProjection | None = None
        if isinstance(raw_map_visual, dict):
            map_visual, calibration_findings = normalize_map_visual(
                raw_map_visual,
                grid_width=geometry.width_squares,
                grid_height=geometry.height_squares,
            )
            presentation_findings.extend(PresentationFinding.model_validate(row) for row in calibration_findings)
        elif raw_map_visual is not None:
            presentation_findings.append(PresentationFinding(
                code="map_visual_invalid",
                severity="ERROR",
                message="The match map visual snapshot is not a typed record. The battlefield geometry remains authoritative.",
            ))

        actor_rows = list(state.get("actors") or [])
        actor_name_by_id = {str(row["entity_id"]): str(row["display_name"]) for row in actor_rows}
        actor_active_by_id = {str(row["entity_id"]): bool(row.get("active")) for row in actor_rows}
        footprint_authority: dict[str, tuple[Any, str, tuple[tuple[int, int], ...]]] = {}
        for row in actor_rows:
            row_id = str(row["entity_id"])
            definition, compatibility_mode = resolve_actor_footprint(row_id)
            anchor_position = Position(x=int(row["position"]["x"]), y=int(row["position"]["y"]))
            footprint_authority[row_id] = (definition, compatibility_mode, definition.occupied_cells(anchor_position))
        actors: list[CombatSheetProjection] = []
        team_runtime_ids: dict[str, set[str]] = defaultdict(set)
        team_actor_ids: dict[str, list[str]] = defaultdict(list)

        for actor in actor_rows:
            actor_id = str(actor["entity_id"])
            catalog_row = projection_by_actor.get(actor_id)
            if catalog_row is None and actor.get("owner_id"):
                owner_catalog = projection_by_actor.get(str(actor["owner_id"]))
                catalog_row = projection_by_actor.get(actor_id) or owner_catalog
            actor_findings: list[PresentationFinding] = []
            if catalog_row is None:
                actor_findings.append(PresentationFinding(
                    code="missing_catalog_projection",
                    severity="ERROR",
                    actor_id=actor_id,
                    message="The actor is present in match state but has no exact accepted catalog projection.",
                ))
                team_id = str(actor.get("team_id") or "team:unassigned")
                team_display = _humanize(team_id) or "Unassigned"
                team_index = 99
            else:
                team_id = str(catalog_row.get("team_id") or "team:unassigned")
                team_display = str(catalog_row.get("team_display_name") or team_by_id.get(team_id, {}).get("display_name") or _humanize(team_id))
                team_index = int(catalog_row.get("team_index", team_by_id.get(team_id, {}).get("team_index", 99)))
            team_runtime_ids[team_id].add(str(actor.get("team_id") or team_id))
            team_actor_ids[team_id].append(actor_id)

            resource_names = self._resource_names(actor_id, actor.get("owner_id"))
            resources = tuple(
                ResourceProjection(
                    resource_id=str(resource_id),
                    display_name=resource_names.get(str(resource_id), _humanize(str(resource_id))),
                    current=int(value),
                    maximum=int((actor.get("resource_maximums") or {}).get(resource_id, value)),
                )
                for resource_id, value in sorted((actor.get("resources") or {}).items())
            )
            conditions_source = actor.get("conditions") or {}
            conditions: list[ConditionProjection] = []
            if isinstance(conditions_source, dict):
                for key, value in sorted(conditions_source.items()):
                    if isinstance(value, dict):
                        condition_id = str(value.get("condition_id") or key)
                        conditions.append(ConditionProjection(
                            condition_id=condition_id,
                            display_name=_humanize(condition_id),
                            stacks=int(value.get("stacks", 1)),
                            source_definition_id=value.get("source_definition_id"),
                            expires_on=value.get("expires_on"),
                        ))
            if not conditions and actor.get("condition_ids"):
                conditions = [
                    ConditionProjection(condition_id=str(value), display_name=_humanize(str(value)))
                    for value in actor.get("condition_ids") or []
                ]

            action_keys = list(actor.get("action_ids") or [])
            reaction_keys = list(actor.get("reaction_ids") or [])
            for candidate in candidates:
                if candidate.actor_id == actor_id and not any(
                    candidate.source_definition_id in {key, (ACTIONS.get(key).source_definition_id if ACTIONS.get(key) else key)}
                    for key in action_keys
                ):
                    action_keys.append(candidate.source_definition_id)
            action_defs: list[ActionDefinitionProjection] = []
            seen_action_ids: set[str] = set()
            for action_key in [*action_keys, *reaction_keys]:
                if action_key in seen_action_ids:
                    actor_findings.append(PresentationFinding(
                        code="duplicate_action_id",
                        severity="ERROR",
                        actor_id=actor_id,
                        action_definition_id=str(action_key),
                        message="The actor definition contains a duplicate action or reaction ID.",
                    ))
                    continue
                seen_action_ids.add(str(action_key))
                runtime = ACTIONS.get(str(action_key))
                action_defs.append(self._action_definition(
                    actor_id,
                    actor.get("owner_id"),
                    str(action_key),
                    runtime,
                    resource_names,
                    actor_findings,
                ))
            availability = tuple(
                self._availability(
                    definition,
                    actor,
                    mode,
                    bool(metadata.get("paused")),
                    state.get("current_actor_id"),
                    candidates,
                )
                for definition in action_defs
            )
            source_actor_id = str(actor.get("owner_id") or actor_id)
            source_envelope = self._projection_by_actor.get(source_actor_id)
            source_projection = source_envelope.get("projection") if source_envelope else None
            character_summary = {
                "path": None,
                "realm": (source_projection or {}).get("realm"),
                "cultivation_level": (source_projection or {}).get("cultivation_level"),
            }
            paths = (source_projection or {}).get("path_effects") or []
            if paths:
                character_summary["path"] = paths[0].get("display_name")
            sheet_link = self._sheet_route(actor, projection_by_actor.get(actor_id), actor_findings)
            owner_id = actor.get("owner_id")
            footprint_definition, footprint_mode, footprint_cells = footprint_authority[actor_id]
            mechanics_authoritative = True
            occupied_by_other = (
                {
                    cell
                    for other_id, (_, _, cells) in footprint_authority.items()
                    if other_id != actor_id and actor_active_by_id.get(other_id, False)
                    for cell in cells
                }
                if actor_active_by_id.get(actor_id, False)
                else set()
            )
            footprint_projection = project_actor_footprint(
                footprint_definition,
                Position(x=int(actor["position"]["x"]), y=int(actor["position"]["y"])),
                grid_width=geometry.width_squares,
                grid_height=geometry.height_squares,
                blocked_cells={(int(cell["x"]), int(cell["y"])) for cell in geometry.blocked_cells},
                occupied_by_other=occupied_by_other,
                mechanics_authoritative=mechanics_authoritative,
                compatibility_mode=footprint_mode,
            )
            if not footprint_projection.in_bounds:
                actor_findings.append(PresentationFinding(
                    code="actor_footprint_out_of_bounds",
                    severity="ERROR",
                    actor_id=actor_id,
                    message="The actor footprint extends outside the authoritative battlefield.",
                ))
            if not footprint_projection.collision_free:
                actor_findings.append(PresentationFinding(
                    code="actor_footprint_collision",
                    severity="ERROR",
                    actor_id=actor_id,
                    message="The actor footprint overlaps blocked geometry or another actor footprint.",
                ))
            actors.append(CombatSheetProjection(
                entity_id=actor_id,
                source_character_id=sheet_link.source_character_id,
                source_character_sheet_identity=sheet_link.character_sheet_identity,
                source_character_revision_sha256=sheet_link.source_revision_sha256,
                display_name=str(actor["display_name"]),
                team_id=team_id,
                runtime_team_id=str(actor.get("team_id") or team_id),
                team_display_name=team_display,
                team_index=team_index,
                primary_combatant=bool(actor.get("primary_combatant")),
                owner_id=str(owner_id) if owner_id else None,
                owner_display_name=actor_name_by_id.get(str(owner_id)) if owner_id else None,
                active=bool(actor.get("active")),
                current_actor=actor_id == state.get("current_actor_id"),
                controller=str(actor.get("control_mode") or "MANUAL"),
                character_summary=character_summary,
                position={"x": int(actor["position"]["x"]), "y": int(actor["position"]["y"])},
                footprint=footprint_projection,
                hit_points={
                    "current": int(actor.get("current_hp", 0)),
                    "maximum": int(actor.get("maximum_hp", 1)),
                    "temporary": int(actor.get("temporary_hp", 0)),
                },
                defenses=(DefenseProjection(defense_id="defense:armor_class", display_name="Defense", value=int(actor.get("armor_class", 0))),),
                speed_ft=int(actor.get("speed_ft", 0)),
                movement_remaining_ft=int(actor.get("movement_remaining_ft", 0)),
                turn_state={
                    "action": bool(actor.get("action_available")),
                    "bonus_action": bool(actor.get("bonus_action_available")),
                    "reaction": bool(actor.get("reaction_available")),
                },
                resources=resources,
                conditions=tuple(conditions),
                action_definitions=tuple(action_defs),
                action_availability=availability,
                features=self._features(actor_id, actor.get("owner_id")),
                visual=self._visual(actor, metadata),
                sheet_link=sheet_link,
                findings=tuple(actor_findings),
            ))
            presentation_findings.extend(actor_findings)

        teams = tuple(
            TeamPresentation(
                team_id=team_id,
                runtime_team_ids=tuple(sorted(team_runtime_ids[team_id])),
                display_name=str(team_by_id.get(team_id, {}).get("display_name") or next((actor.team_display_name for actor in actors if actor.team_id == team_id), _humanize(team_id))),
                team_index=int(team_by_id.get(team_id, {}).get("team_index", next((actor.team_index for actor in actors if actor.team_id == team_id), 99))),
                actor_ids=tuple(team_actor_ids[team_id]),
            )
            for team_id in sorted(team_actor_ids, key=lambda value: (
                int(team_by_id.get(value, {}).get("team_index", 99)), value
            ))
        )
        boundary_projection = None
        if mode == "HISTORY" and boundary is not None:
            boundary_projection = HistoricalBoundaryProjection(
                boundary_index=int(boundary["boundary_index"]),
                record_sequence=boundary.get("record_sequence"),
                transaction_id=boundary.get("transaction_id"),
                step_label=str(boundary.get("step_label") or f"Historical step {boundary['boundary_index']}"),
                canonical_state_sha256=boundary.get("canonical_state_sha256"),
            )
        return CombatPresentationProjection(
            match_id=match_id,
            display_name=str(metadata.get("display_name") or match_id),
            mode=mode,
            state_version=int(state.get("state_version", 0)),
            boundary=boundary_projection,
            round_number=int(state.get("round_number", 0)),
            current_slot_index=int(state.get("current_slot_index", 0)),
            current_actor_id=state.get("current_actor_id"),
            paused=bool(metadata.get("paused")),
            terminal=state.get("terminal_result") is not None,
            terminal_result=state.get("terminal_result"),
            battlefield=geometry,
            map_visual=map_visual,
            teams=teams,
            actors=tuple(actors),
            initiative_order=tuple(state.get("initiative_order") or []),
            zones=tuple(state.get("zones") or []),
            feed=feed,
            findings=tuple(presentation_findings),
        )
